name: Promote (DEV/QA/UAT/PROD) with checkboxes

on:
  repository_dispatch:
    types: [promote_request]   # from app repos
  workflow_dispatch:
    inputs:
      repo_full_name:
        description: "owner/repo (auto-filled if coming from dispatch)"
        required: false
      sha:
        description: "Commit SHA (auto-filled if coming from dispatch)"
        required: false
      deploy_dev:
        type: boolean
        description: "Deploy to DEV"
        required: true
        default: true
      deploy_qa:
        type: boolean
        description: "Deploy to QA"
        required: true
        default: true
      deploy_uat:
        type: boolean
        description: "Deploy to UAT"
        required: true
        default: true
      deploy_prod:
        type: boolean
        description: "Deploy to PROD"
        required: true
        default: false

permissions:
  id-token: write         # REQUIRED for GitHub OIDC
  contents: read

env:
  ORG_REPO_PAT: ${{ secrets.ORG_REPO_PAT }}

concurrency:
  group: promote-${{ inputs.repo_full_name || github.event.client_payload.repo_full_name }}-${{ inputs.sha || github.event.client_payload.sha }}
  cancel-in-progress: false

jobs:
  resolve:
    runs-on: ubuntu-latest
    outputs:
      repo: ${{ steps.o.outputs.repo }}
      sha: ${{ steps.o.outputs.sha }}
      dev: ${{ steps.o.outputs.dev }}
      qa:  ${{ steps.o.outputs.qa }}
      uat: ${{ steps.o.outputs.uat }}
      prod:${{ steps.o.outputs.prod }}
    steps:
      - id: o
        run: |
          repo="${{ github.event.client_payload.repo_full_name || inputs.repo_full_name }}"
          sha="${{ github.event.client_payload.sha || inputs.sha }}"
          dev="${{ inputs.deploy_dev }}"
          qa="${{ inputs.deploy_qa }}"
          uat="${{ inputs.deploy_uat }}"
          prod="${{ inputs.deploy_prod }}"
          echo "repo=$repo" >> $GITHUB_OUTPUT
          echo "sha=$sha" >> $GITHUB_OUTPUT
          echo "dev=$dev" >> $GITHUB_OUTPUT
          echo "qa=$qa" >> $GITHUB_OUTPUT
          echo "uat=$uat" >> $GITHUB_OUTPUT
          echo "prod=$prod" >> $GITHUB_OUTPUT

  dev:
    needs: resolve
    if: ${{ needs.resolve.outputs.dev == 'true' }}
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout target repo@sha
        uses: actions/checkout@v4
        with:
          repository: ${{ needs.resolve.outputs.repo }}
          ref: ${{ needs.resolve.outputs.sha }}
          token: ${{ env.ORG_REPO_PAT }}

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks -v

      # Native GitHub→Databricks OIDC (no PAT/az login)
      - name: Verify auth (DEV)
        env:
          DATABRICKS_AUTH_TYPE: github-oidc
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_ID }}
        run: |
          databricks current-user || true
          databricks workspace ls / || true
          echo "Auth ready for DEV"

      - name: Validate bundle (DEV)
        env:
          DATABRICKS_AUTH_TYPE: github-oidc
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_ID }}
        run: databricks bundle validate -t dev

      - name: Deploy bundle to DEV
        env:
          DATABRICKS_AUTH_TYPE: github-oidc
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_ID }}
        run: databricks bundle deploy -t dev

  qa:
    needs: resolve
    if: ${{ needs.resolve.outputs.qa == 'true' }}
    runs-on: ubuntu-latest
    environment: QA
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ needs.resolve.outputs.repo }}
          ref: ${{ needs.resolve.outputs.sha }}
          token: ${{ env.ORG_REPO_PAT }}

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks -v

      - name: Auth (QA)
        env:
          DATABRICKS_AUTH_TYPE: github-oidc
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_ID }}
        run: echo "Auth ok (QA)"

      - name: Validate QA
        env:
          DATABRICKS_AUTH_TYPE: github-oidc
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_ID }}
        run: databricks bundle validate -t qa

      - name: Deploy QA
        env:
          DATABRICKS_AUTH_TYPE: github-oidc
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_ID }}
        run: databricks bundle deploy -t qa

  uat:
    needs: [resolve, qa]
    if: ${{ needs.resolve.outputs.uat == 'true' && (needs.qa.result == 'success' || needs.resolve.outputs.qa == 'false') }}
    runs-on: ubuntu-latest
    environment: UAT
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ needs.resolve.outputs.repo }}
          ref: ${{ needs.resolve.outputs.sha }}
          token: ${{ env.ORG_REPO_PAT }}

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks -v

      - name: Auth (UAT)
        env:
          DATABRICKS_AUTH_TYPE: github-oidc
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_ID }}
        run: echo "Auth ok (UAT)"

      - name: Validate UAT
        env:
          DATABRICKS_AUTH_TYPE: github-oidc
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_ID }}
        run: databricks bundle validate -t uat

      - name: Deploy UAT
        env:
          DATABRICKS_AUTH_TYPE: github-oidc
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_ID }}
        run: databricks bundle deploy -t uat

  prod:
    needs: [resolve, uat, qa]
    if: ${{ needs.resolve.outputs.prod == 'true' &&
            (needs.uat.result == 'success' || needs.resolve.outputs.uat == 'false') &&
            (needs.qa.result  == 'success' || needs.resolve.outputs.qa  == 'false') }}
    runs-on: ubuntu-latest
    environment: PROD
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ needs.resolve.outputs.repo }}
          ref: ${{ needs.resolve.outputs.sha }}
          token: ${{ env.ORG_REPO_PAT }}

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks -v

      - name: Auth (PROD)
        env:
          DATABRICKS_AUTH_TYPE: github-oidc
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_ID }}
        run: echo "Auth ok (PROD)"

      - name: Validate PROD
        env:
          DATABRICKS_AUTH_TYPE: github-oidc
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_ID }}
        run: databricks bundle validate -t prod

      - name: Deploy PROD
        env:
          DATABRICKS_AUTH_TYPE: github-oidc
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_CLIENT_ID: ${{ secrets.DATABRICKS_ID }}
        run: databricks bundle deploy -t prod
